newrelic/serverless-newrelic-lambda-layers

README.md, src/index.ts
Add optional configuration to specify a custom filter for the CloudWatch log subscription.
Configuration defaults to the standard "NR_LAMBDA_MONITORING" filter.
If the filter is configured as "*" it will capture all logs.
If multiple filters are provided they are combined into an OR filter.
=> Cloud watch filter

src/index.ts
Checks for non-array filter input, and uses the more-performant `.indexOf()` in place of `.find()`.
Closes #19
=> Adding fallback type checking on cloudWatchFilter input

package.json
NPM isn't happy with un-bumped package.json version
=> Version needs to be bumped before publishing.

package.json
OK, *this* release should stick.
=> Forcing new version to keep package.json in sync with release.

package.json, src/index.ts
After configuring `serverless-webpack` I've noticed that *NewRelic* configuration is not being generated. With a little bit debugging I found the problem with `for each` and replaced with `for .. of`. 
Placed the link that explain the problem below:
https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop
And output after adding console log:
*forEach*
*for..of*
I hope it helps.
=> Replace forEach with for..of to allow promise to complete

README.md, package.json, src/index.ts
Replaced outstanding `forEach` with `for..of` to fix promise errors. 
Added to optional properties *logIngestionFunctionName* and *disableAutoSubscription* for details refer to https://github.com/iopipe/serverless-newrelic-lambda-layers/issues/27
=> Disable auto subscription, log ingestion function parameterization, replaced forEach with for .. of

package.json, src/index.ts
Changing default filter pattern to avoid errors on deployment, and to pass tslint.
Bumping version to 0.1.12
=> Fixing default filter pattern

src/index.ts
Converting default filter patterns to array, which avoids double-wrapping the patterns when they're joined.
=> Fixing default pattern definition to avoid double-wrapping

.gitignore, README.md, examples/nodejs/serverless.yml, jest.config.js, package-lock.json, package.json, src/index.ts, tests/fixtures/debug-log-level.input.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.input.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/log-disabled.input.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-level.input.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.input.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.input.service.json, tests/fixtures/provider-environment.output.service.json, tests/index.test.ts
Hello, 
It's been a while but priorities have changed in my company but now I'm back on NewRelic implementation and would like to extend the implementation to support some of our requirements which we find a little bit awkward to work with.
We found a configuring log level a little bit limited especially when we have multiple functions. We have to configure `NEW_RELIC_LOG_LEVEL` for each function instead of having one place to do that. NewRelic in `info` logs quite a lot of details which are not use for us. 
To achieve that we have to override each function individually. I would propose to change that to:
1. new property `logLevel` which can accept any of the `pino` supported values
2. deprecate `debug` option but keep it for backward compatibility 
3. still be able to override global …
=> log level with test introduction

package-lock.json, package.json
A few releases have failed CircleCI lint checks, so this ensures that we run tslint with each commit. (Thanks for the suggestion about Husky, @kamaz !)
=> Adding Husky to enable pre-commit lint check

README.md, package-lock.json, package.json, src/index.ts, tests/fixtures/include-exclude.input.service.json, tests/fixtures/include-exclude.output.service.json, tests/fixtures/include.input.service.json, tests/fixtures/include.output.service.json
In some cases, we found an exclude option a little bit awkward especially when you have only a single function to apply Layer on. 
I've added an include option which works as exclude but instead includes functions.
=> enable to include functions versus exclude

README.md, package.json, src/index.ts, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-excluded.input.service.json, tests/fixtures/stage-excluded.output.service.json, tests/fixtures/stage-included.input.service.json, tests/fixtures/stage-included.output.service.json
=> limit plugin to specific stages

package.json, src/index.ts, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-included.output.service.json, tests/index.test.ts
I made `shouldSkipPlugin()` less error-prone. Now it doesn't have to be added into each hook and instead runs in the constructor
As a result, I had to make a change to the test as well. Instead of calling it directly, I call it via a lifecycle hook
=> moved shouldSkipPlugin to constructor

package-lock.json, package.json, src/api.ts
=> Add fetch dependency

README.md, package.json, src/index.ts, src/integration.ts, templates/nr-license-key-secret.yaml, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-included.output.service.json
Adding the option of supporting the Lambda extension for sending telemetry as an alternative to CW log subscriptions.
If `enableExtension` is true and the `apiKey` is set (and valid), the plugin stores the NR license key in a managed secret, if the secret doesn't already exist. If it doesn't exist and can't be created, the plugin falls back to setting the license key as a function environment variable. If there's no license key set, the plugin falls back to CW log subscription.
=> feat: Support Lambda Extension for ingest

README.md, examples/nodejs/serverless.yml, examples/python/serverless.yml, package.json, src/index.ts, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/include-exclude.input.service.json, tests/fixtures/include-exclude.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.input.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.input.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.input.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-included.output.service.json
From test output, I found that the plugin wasn't disabling the extension when enableExtension was set to `false` in the serverless.yml. This fixes that, adds test coverage, updates serverless.yml examples, and tweaks the test-generation script.
=> fix: Plugin should disable ext when asked

package.json, src/index.ts, src/integration.ts, tests/index.test.ts
On deploy, this version of the plugin checks for the existence of a secret access policy named with the current region. If found, it provides the policy ARN to serverless's generated CF template as a ManagedPolicyArn, so that the function can access the license key secret for authenticating the extension.
If the policy is not found for the function's region, the plugin creates the secret and policy. If the license key isn't found, the plugin falls back to ingestion via the ingestion lambda and CloudWatch Log Subscription.
=> fix: Add access policy to execution role

examples/nodejs/package-lock.json, examples/nodejs/package.json, examples/python-requirements/package-lock.json, examples/python-requirements/package.json, examples/python/package-lock.json, examples/python/package.json, package-lock.json, package.json, tests/index.test.ts
Updating serverless and jest to their latest versions, and updating versions in examples in response to Dependabot. (Local tests work; needs an end-to-end, which I'll do this coming week.
Also, this should probably merge *after* the policy update in #100
=> fix: Update dependencies

README.md
Bumping this for our github readme to show the SLS update. I don't think this needs a full release, though.
=> fix: Bump sls version in ReadMe

src/integration.ts
When passing accountId as an env var it wasn't properly being compared to the returned account id from the graphql integration check because of strict equality comparing numbers to strings. 
https://newrelic.atlassian.net/browse/LAMBDA-1083
=> chore: converting accountId to number before comparing to integrated accounts in NR

README.md, package-lock.json, package.json, src/api.ts, src/index.ts, src/integration.ts, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.input.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tsconfig.json
Resolves #143.
Add a configuration option to set a network request proxy so that HTTP requests from the plugin work when behind a proxy. 
Many businesses operate behind a web proxy to control and monitor internet access. Those businesses can not use the latest versions of the plugin without the ability to navigate a proxy.
I looked into setting this without using a new dependency, but judged that it was more hassle than it was worth to configure an HTTP proxy using the low-level NodeJS HTTP Agent. The [node-https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent) package is the commonly referenced way to configure a proxy with `node-fetch`.
=> feat: Add 'proxy' option in order to allow this plugin to work behind an HTTP proxy

package-lock.json, package.json, src/api.ts, src/index.ts, src/integration.ts, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json
A user with ~90 functions was encountering sporadic bad gateway errors. Initially this seemed to be during the call to the layers API, but the result of that first call is cached, and that number of requests in a short time period should be well within the API's performance capabilities. It also has no rate limiting.
We did not have error logging around other http calls, though, particularly to NR servers and AWS. This adds some error logging for those cases.
=> Improve logging around http calls 

package-lock.json, package.json, src/index.ts, tests/fixtures/trusted-account-key-excluded.input.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.input.service.json, tests/fixtures/trusted-account-key-included.output.service.json
[A community-submitted PR](https://github.com/newrelic/serverless-newrelic-lambda-layers/pull/146) fixes the issue, but base code and layer versions have changed. This PR incorporates those changes and relevant tests.
=> fix: Patch for trusted account key

examples/nodejs/serverless.yml, package-lock.json, package.json, src/index.ts, tests/fixtures/arm64.input.service.json, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
This PR adds support for the serverless.com post-2.61 provider.architecture property, and queries our layers API accordingly.
This also updates jest-related dependencies, in response to security notices.
=> feat: Add support for ARM64 architecture

README.md
The example given for the `stages` option was incorrectly formatted and this caused a production bug for us because we used `include:` instead of `stages:`! 😄
=> docs: fix documentation error

package.json, src/api.ts, src/integration.ts
...or when `enableIntegration` is undefined or false.
=> fix: Skip creating integration when MS or polling integrations exist

.circleci/config.yml
Can be directed at `master` once LAMBDA-1356 is closed, or merged into 1356.
=> fix: Updating build container to Node 12, Node 10 having been EOL'd.

examples/java/pom.xml, package-lock.json, package.json
This dependency has been updated again, so this updates our example pom file.
=> Update aws-lambda-java-log4j2 to 1.5.0

src/index.ts, tests/fixtures/arm64-unsupported.output.service.json
This PR duplicates the architectural change in #162 , but doesn't remove old runtimes. I've made this second PR in case new regions support ARM64 before we release layers there.
=> Refactoring architecture query

package-lock.json, package.json, src/api.ts, src/index.ts, src/integration.ts
node-fetch 2.6.7 is patched.
Prettier.js is updated, and has slight API changes that require some changes to code style: trailing commas and parens around the param of single-param arrow functions. This gets us up to date with Prettier. 
=> Updating dependencies

.circleci/config.yml, README.md, package-lock.json, package.json, src/api.ts, src/index.ts, src/integration.ts, src/utils.ts, tests/index.test.ts
Updating, addressing breaking changes, adding log dependencies, updating CircleCI image to Node 14 (preferred version for Serverless now).
Serverless 3.0 deprecates `serverless.cli.log` in favor of BYOL. The `log` dependency was already in the project, so it seemed like a natural replacement.
Serverless is now assuming a standard runtime of Node 14, so this also bumps the container build version.
=> Updating serverless to 3.0

README.md
The example for `stages` is not correct. The `stages` block should be inside the `newRelic` block to make it work.
=> doc: fix example of stages config

package.json, src/index.ts, src/integration.ts
Serverless 3.x introduced a breaking change for logging. Some customers are using the latest plugin with Serverless 2.x, so for that case, this PR would print a warning. 
=> Check for Serverless 3.x and provide a fallback logging interface

README.md, package-lock.json, package.json, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.input.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Now that Node 16 layers are out, here's support from the plugin (with updated snapshots and one test with Node 16 as the target.)
=> Support Node 16

package-lock.json, package.json, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Agents need this in serverless mode. Closes #250
=> Restoring NEW_RELIC_LOG_ENABLED env var

.husky/pre-commit, package-lock.json, package.json
A just-merged dependency update resulted in an updated version of husky, which used a different config structure. This updates the project. If you encounter an error on commit, you may need to run the husky project's updater: https://github.com/typicode/husky-4-to-8
We need to bump plugin version manually for release. 
=> chore: Updated version, updated husky

.circleci/config.yml, jest.config.js, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json, tests/index.test.ts
This PR reproduces https://github.com/newrelic/serverless-newrelic-lambda-layers/pull/289 , which uses Jest to generate code coverage, and adds the snapshot tests to CI. 
This PR also adds one commit to fix a CI error from that PR: the serverless dependency changed the capitalization of one filename. Also, this updates the CircleCI image used.
=> NR-60814 Collect code coverage

src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.input.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
I have a service with several functions that were working fine with `serverless-newrelic-lambda-layers`, but then I added a new function that needed its own `layers` definition within the function:
```
functions:
mySpecialFunction:
layers:
- arn:aws:lambda:us-east-1:123456789012:layer:SomeSpecialLayer:1
```
When I added this new function, it did not have access to `newrelic_lambda_wrapper`:
```
Runtime.ImportModuleError: Unable to import module 'newrelic_lambda_wrapper': No module named 'newrelic_lambda_wrapper'
```
It turns out that if `layers` is specified under a function, it will override (not merge with) any layers at the provider level.
This should fix things by adding the New Relic layer to functions that have any `layers` already defined, even if `shouldUseProviderLayers` is …
=> Fix NR not accessible to a function with layers defined

README.md, src/index.ts, tests/fixtures/arm64-unsupported.input.service.json, tests/fixtures/arm64-unsupported.output.service.json, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
* adjusted tests as new version of layers exist
* remove arm64 unsupported test for nodejs14.x in region ap as it has now support of it
=> Support nodejs18.x as the lambda layers are not build

package-lock.json, package.json
Version 3.4.0 now supports Node 18.
=> chore: Updated version for release

.circleci/config.yml, examples/nodejs/package-lock.json, package-lock.json, package.json, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
* Added lockfile checks to CI workflow to prevent malicious changes
Part of NEWRELIC-5683
Supercedes #310 and #311 
We have an attack vector being open source and being used by many customers.  It is very hard to spot supply chain attacks especially if we aren't on high alert and not scrutinizing package-lock updates from community.  There is a tool created by a devrel at snyk to address this issue.  You can read more about [supply chain attacks here](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/).
Note that this is a bigger diff in package-lock.json due to npm changing from sha1 to sha512, and the only way to fix is to regenerate the lockfile.
=> NEWRELIC-5683 added lockfile checks/linting to CI workflow

examples/java/package-lock.json, examples/nodejs/package-lock.json, examples/python-requirements/package-lock.json, examples/python/package-lock.json, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
This PR replaces four PRs from dependabot. This updates cookiejar to 2.1.4 in examples, and updates test fixtures (which blocked the other PRs).
Closes NR-82367.
=> Updated cookiejar dependency in examples

package-lock.json, package.json, src/utils.ts, tslint.json
This package is used for one function that can easily be replaced with a core library function.
Closes #348
=> chore(package): remove fs-extra

package.json, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Closes [NEWRELIC-8823](https://issues.newrelic.com/browse/NEWRELIC-8823) 
Closes https://github.com/newrelic/serverless-newrelic-lambda-layers/issues/354
Awaiting release of Python 3.10 layers for older regions.
=> Support for python 3.10

.github/workflows/repolinter.yml, README.md
It was brought to our attention this lacked a New Relic OSS header.  It's a community plus project, I also added repolinter
=> chore: add OSS community plus header and repolinter

src/index.ts
Fixes an error when looking to see if `this.config.enableExtensionLogs` is disabled.
=> fix boolean sense of test for enableExtensionLogs

README.md, package-lock.json, package.json, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
This PR updates the supported runtimes list for Python and Node.
Changes:
- Drop Python 3.6 and Node 12
- Add Python 3.10 and Python 3.11
Related issue: #373
=> Update supported runtimes list for Python and Node

src/integration.ts
This PR updates to ensure the `account` is not a null value. Otherwise a type error is thrown on ln 59.
=> Handle null account values returned from NR API.

.circleci/config.yml, package.json, src/integration.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json, tests/index.test.ts, tests/integration.test.ts, tests/paginatedResults.json
Customers with more than 100 locally-scoped IAM policies could encounter an error in which the plugin tries to recreate the secret access policy. This change follows the ListPolicies pagination standard. 
Closes #357 
Closes NR-154677
=> fix: Updated integration to allow for paginated ListPolicies

README.md, examples/nodejs/serverless.yml, package.json, src/index.ts, tests/fixtures/manual-wrapping.input.service.json, tests/fixtures/manual-wrapping.output.service.json
Some functions with many dependencies may see longer cold-start times due to the need to load them all in before the function's invoked. For those situations, we're adding the ability to skip dynamic wrapping, on the assumption that the user will wrap manually. Even if we avoid dynamic wrapping, the user can still take advantage of the plugin's automatic setting of environment variables, getting the latest layer, and setting up access to the license key. 
Closes #377 
Closes NR-152247
=> feat: Added manualWrapping flag to skip wrapping

README.md, package.json, src/index.ts, tests/fixtures/debug.input.service.json, tests/fixtures/debug.output.service.json
Node 14 is [no longer supported](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) as a Lambda runtime. This PR drops support for it.
=> chore!: Dropped support for Node 14

.github/workflows/add-to-board.yml
This workflow should add all new issues and PRs to our [Node board](https://github.com/orgs/newrelic/projects/41)
=> chore: adds a workflow to add any new issues or prs to our GH engineering board

.github/workflows/ci-workflow.yml
This plugin's auto-release process is failing validation with GitHub's REST API at the Create Release Notes step (run from the Node Agent's reusable workflow), here: https://github.com/newrelic/node-newrelic/blob/main/bin/prepare-release.js#L184
One difference between this plugin repo and other repos is that the main CI Workflow file has been set to v4 of actions, while the agent uses v3. This repo's prepare-release action isn't initiated from the ci-workflow file, though, so this may not be an important difference. If nothing else, reverting these to v3 will make this repo consistent with other repos.
=> chore(ci): Reverted ci to GHA v3

README.md, package.json, src/index.ts
This PR adds the `provided.al2` runtime to the `wrappableRuntimeList` maintained in `index.ts`. From my testing, [there are NewRelic layers supporting this runtime](https://us-east-2.layers.newrelic-external.com/get-layers?CompatibleRuntime=provided.al2).
I used the version of the package in this PR to deploy an application, and verified that logs were being forwarded.
N/A
=> Add `provided.al2` to supported runtimes.

README.md, src/index.ts
- provided.al2023 can be used with Go functions
- prevents the following issue
```
Warning: Unsupported runtime "provided.al2023" for NewRelic layer; skipping.
```
- depends on an update to supported runtimes for the extension
https://github.com/newrelic/newrelic-lambda-layers/issues/268
=> feat: add provided.al2023

README.md, src/index.ts
Adding support for python 3.13 runtime.
- Created new python example using serverless.
- Updated serverless version to `4.4.13` (latest)
- Built the changed plugin.
- Now added below serverless.yml 
```
service: newrelic-lambda-python-313
provider:
name: aws
stage: prod
region: us-east-1
stackTags:
environment: us-testing
owning_team: LAMBDA
product: aws-lambda
tags:
environment: us-testing
owning_team: LAMBDA
product: aws-lambda
plugins:
- ./.serverless_plugins/serverless-newrelic-lambda-layers
custom:
newRelic:
accountId: ${env:NEW_RELIC_ACCOUNT_ID}
apiKey: ${env:NEW_RELIC_PERSONAL_API_KEY}
debug: true
functions:
layer-python313:
events:
- schedule: rate(5 minutes)
handler: handler.handler
package:
patterns:
- '!./**'
- 'handler.py'
runtime: python3.13
```
- Now updated the above using …
=> feat: Added support for Python 3.13 runtime

README.md, package-lock.json, package.json, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.input.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
- This PR helps to support the Nodejs v22 runtime.
- Updates few test cases
- remove serverless v1 and v2 since we support serverless v3 and v4.
=> feat: Adding support to Node js v22 runtime and updating test cases.

README.md, src/index.ts
This PR introduces two new optional configurations to enhance log event tagging for New Relic:
- Allows specifying tags to be added to all log events.
- Tags are formatted as colon-delimited key-value pairs.
- Multiple key-value pairs can be separated by semicolons (`;`).
- Example usage:
```yaml
custom:
newRelic:
nrTags: 'env:prod;team:myTeam'
```
- Provides an alternative delimiter option for `NR_TAGS`, useful for UTF-8 environments where semicolon (`;`) may cause issues.
- Lets users set a custom delimiter instead of using the default semicolon.
- Example usage:
```yaml
custom:
newRelic:
nrEnvDelimiter: ','
```
Resolves #492
=> feat: added feature to add nrTags and customise nrEnvDelimiter

examples/nodejs/package.json, examples/python-requirements/package.json, examples/python/package.json
[Serverless](https://www.serverless.com/) version in the following examples were updated to latest version of `4.12.0`:
- Python
- Python-requirements
- Nodejs
=> chore: Updated Serverless version in examples

package-lock.json, package.json, src/index.ts, src/integration.ts, tests/fixtures/api-and-ingest-key.input.service.json, tests/fixtures/api-and-ingest-key.output.service.json, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/ingest-key-only.input.service.json, tests/fixtures/ingest-key-only.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json, tests/index.test.ts
This PR introduces support for Ingest license keys in the CLI, allowing customers to use `Ingest` keys in their serverless configurations. 
To test the new Ingest key support:
- Update your serverless.yml configuration file.
- Replace the variable apikey with ingestKey.
- Assign your Ingest Key to the ingestKey field.
```
custom:
newRelic:
accountId: <Account-ID>
ingestKey: <Ingest-Key>
```
Deploy your serverless application to ensure the Ingest key is being used correctly.
This PR adds support for Ingest license keys by:
- Update to use ingestKey if available in configureLicenseForExtension.
Key Check Logic:
- Adjust checks to accept either apiKey or ingestKey.
- Skip integration checks when using ingestKey.
- Improve error messages to include ingestKey details.
[NR-440836]: …
=> feat: Support for Ingest Key
