newrelic/serverless-newrelic-lambda-layers

examples/nodejs/serverless.yml, examples/python/serverless.yml
=> Add resource tags

README.md, examples/nodejs/handler.js, examples/nodejs/serverless.yml, src/index.ts
=> Add nodejs12.x Support

README.md, examples/python/serverless.yml, package.json, src/index.ts
=> Add python3.8 Runtime Support

package.json, src/index.ts
=> Updating plugin name in plugin order checking

.gitignore, src/index.ts
Runs lint --fix on index.ts
Adds .DS_Store to .gitignore
Required to pass CircleCI.
=> Linting to pass CircleCI checks

src/index.ts
=> Add warning if competing subscription filter detected

README.md
=> Update README requirements to reflect new CLI

src/index.ts
=> Handle case where plugins is an object

src/index.ts
=> Update Default Subscription Filter Pattern

package.json, src/index.ts
Correcting linting errors; bumping version to avoid CircleCI/npm complaint
=> Delinting attempted release

package-lock.json, package.json, src/index.ts, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json
=> Optimize Async Calls; Update Fixtures

package.json
=> Release v0.1.19

README.md, src/api.ts, src/index.ts, src/integration.ts, src/utils.ts
- Creation of NR Integration if none found and enableIntegration set to yes
- use of api key instead of license key
- Updating readme to match cli required variables
=> NR Integration config

README.md, src/api.ts, src/index.ts, src/integration.ts
- Renamed `newRelic.newRelicApiKey` to `newRelic.apiKey` in config
- Made `linkedAccount` optional with a default value
- Some `README` updates
=> Preparing a v0.2.0 Release

package.json, src/integration.ts
=> Fix getCallerIdentity Reference

package.json, src/index.ts
=> Fix Integration Check Binding

package.json
=> Include templates directory in npm package

package-lock.json, package.json, src/index.ts, tests/fixtures/debug-log-level.input.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.input.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/include-exclude.input.service.json, tests/fixtures/include-exclude.output.service.json, tests/fixtures/include.input.service.json, tests/fixtures/include.output.service.json, tests/fixtures/log-disabled.input.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-level.input.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.input.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.input.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-excluded.input.service.json, tests/fixtures/stage-excluded.output.service.json, tests/fixtures/stage-included.input.service.json, tests/fixtures/stage-included.output.service.json
request dependency still required as peer, but the response interface has changed. Test fixture updates also required, so those are added as well.
=> Mrickard/lambda 863/fix request for layers

package.json
Bumps package.json version for release pipeline
=> fix: Version bump for release pipeline

README.md, package-lock.json, package.json, src/index.ts, templates/nr-license-key-secret.yaml, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-included.output.service.json
Linked issue: https://newrelic.atlassian.net/browse/LAMBDA-1003
=> feat: Explain if license key fails validation

package-lock.json, src/index.ts
Ticket: https://support.newrelic.com/hc/requests/442572
=> Fixed region not resolving in constructor

package-lock.json, package.json
Bump for release of region patch.
=> chore: version bump to 1.1.1

examples/nodejs/serverless.yml, src/index.ts, tests/fixtures/debug-log-level.input.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.input.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/eu.input.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include-exclude.input.service.json, tests/fixtures/include-exclude.output.service.json, tests/fixtures/include.input.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.input.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.input.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/log-disabled.input.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.input.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.input.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.input.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.input.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-excluded.input.service.json, tests/fixtures/stage-excluded.output.service.json, tests/fixtures/stage-included.input.service.json, tests/fixtures/stage-included.output.service.json
Draft pull request until node 14 layers are published
=> feat: Add node 14 support

README.md, package.json, src/index.ts, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.input.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-included.output.service.json
This fixes https://github.com/newrelic/serverless-newrelic-lambda-layers/issues/114
=> Added disableLicenseKeySecret flag

README.md, package-lock.json, package.json
Addresses these issues:
#112 (nrRegion: 'eu' added to readme)
#113 (Node 14 added to readme)
#117 (Link to serverless docs for template variables)
=> fix: Updates to ReadMe

examples/java/src/main/java/com/serverless/Handler.java
I had left some code accidentally that referenced a class that had been removed. Fixing that here.
=> Fix of example

package-lock.json, package.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/stage-included.output.service.json
Updating serverless and its dependencies. This next release includes other recent dependency updates as well. This also converts package-lock.json to version 2, resulting in a large diff.
=> Updating dependencies

examples/java/package-lock.json, examples/java/package.json, examples/nodejs/package-lock.json, examples/nodejs/package.json, examples/python-requirements/package-lock.json, examples/python-requirements/package.json, examples/python/package-lock.json, examples/python/package.json, package-lock.json
Redoing example dependencies to avoid conflicts.
=> fix: Updating dependencies and lockfile in examples

.circleci/config.yml, examples/java/package-lock.json, examples/java/package.json, examples/nodejs/package-lock.json, examples/nodejs/package.json, examples/python-requirements/package-lock.json, examples/python-requirements/package.json, examples/python/package-lock.json, examples/python/package.json, package-lock.json, package.json
Updating to respond to dependabot notifications
=> fix: Updating dependencies

package-lock.json, package.json
=> fix: Updating serverless to 2.59

package.json, tests/fixtures/arm64-unsupported.input.service.json, tests/fixtures/arm64-unsupported.output.service.json
=> chore: Adding test for regions without ARM64 support

src/index.ts, src/integration.ts
=> fix: Ensuring that integration will be created if configured

README.md, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
=> Updating ReadMe for NPM/node version notes

package-lock.json, src/index.ts, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/includes-all-provider-layer.input.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/provider-layer.input.service.json, tests/fixtures/provider-layer.output.service.json
This is to address https://github.com/newrelic/serverless-newrelic-lambda-layers/issues/242
=> Using provider level layers instead of function level layers

package-lock.json, package.json
=> chore: Update version to 3.2.0

package-lock.json, package.json, src/index.ts
Updating to match the stack name used by the CLI.
Closes #254 
=> Update ingest script stack name

package-lock.json, package.json
=> chore: Updated version for release

tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
=> chore: Updated test fixtures

package-lock.json, package.json
=> chore: Bump version to 3.4.2 for release

examples/java/package-lock.json, examples/nodejs/package-lock.json, examples/python-requirements/package-lock.json, examples/python/package-lock.json, package-lock.json, package.json, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Dependency and test fixture update.
Closes NEWRELIC-6538
=> chore(deps): bump simple-git to 3.16.0

README.md, package-lock.json, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Adds support for using the new java 17 layer added in https://github.com/newrelic/newrelic-lambda-layers/issues/152
=> Add java 17 support

package-lock.json, package.json
* Added support for Java 17 layer (thank you to @michjacobs!)
* Updated dependencies
=> chore: Release v4.2.0

examples/java/package-lock.json, examples/nodejs/package-lock.json, examples/python-requirements/package-lock.json, package-lock.json
This PR consolidates four Dependabot PRs that needed to be rebased before merging.
=> chore(deps): Updated follow-redirects

README.md, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Adds support for using the new java 17 layer added in [newrelic/newrelic-lambda-layers#210](https://github.com/newrelic/newrelic-lambda-layers/pull/210)
=> feat: Added Java 21 support

CHANGELOG.md, changelog.json
The agent repo release process expects a changelog.json file in addition to a CHANGELOG.md. This adds one. 
Closes #422 
Closes NR-252073
=> chore(ci): Added changelog.json to unblock release 

tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Please provide a brief description of the changes introduced in this pull request.
What problem does it solve? What is the context of this change?
Please describe how you have tested these changes. Have you run the code against an example application?
What steps did you take to ensure that the changes are working correctly?
Please include any related issues or pull requests in this section, using the format `Closes #<issue number>` or `Fixes #<issue number>` if applicable.
=> test: Updated ARNs to contain latest layer versions

.github/workflows/ci-workflow.yml, package-lock.json, package.json, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Updated the lambda layer version to the latest layer version for the node in test case
=> test(layer): upgrade Lambda layer version in tests NR-278207

.github/workflows/create-release.yml, CHANGELOG.md
This adds the `build: true` to create release which should build the package before publishing.
Please describe how you have tested these changes. Have you run the code against an example application?
What steps did you take to ensure that the changes are working correctly?
Closes #449
=> ci: Updated create release to pass in `build: true`

src/index.ts, tests/fixtures/arm64-unsupported.output.service.json, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Description
This code helps to update all the Layer ARN's to latest versions to pass the github PR validations.
How to Test
Raise any PR and you can see that snapshot tests are being passed after this PR.
=> feat: Updating the Layer ARN versions to latest

package-lock.json, package.json
Adding support to serverless v4.
Closes https://github.com/newrelic/serverless-newrelic-lambda-layers/issues/466 , https://github.com/newrelic/serverless-newrelic-lambda-layers/issues/467.
=> security(deps): adding support to serverless v4

README.md
This PR updates the readme file as per latest release.
=> docs: update readme as per latest release

.github/workflows/ci-workflow.yml
Updating code cov version that helps in removing errors of code coverage.
=> feat: updating code cov version

tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
- Solves test case issue for v22
=> chore: modified test cases for node js 22

examples/nodejs/serverless.yml, examples/python-requirements/package.json, examples/python-requirements/serverless.yml, examples/python/serverless.yml, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
Details: Updated versions for the languages in the serverless-example.
=> chore: Updated examples with latest versions

README.md, src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
- This PR solves the issue for snapshots tests failing.
=> chore: updated test fixures for the serverless repo with latest layers

tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
- This PR is to update the test-fixtures with latest layer versions
=> chore: updating test-fixtures with latest versions

.github/workflows/ci-workflow.yml
=> chore: update ci-workflow.yml

examples/java/pom.xml
- I have tested and updated the Java example dependencies to align with the latest available versions.
[NR-404765]: https://new-relic.atlassian.net/browse/NR-404765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: updated dependencies version

package-lock.json
- This PR resolves `package-lock.json` issue with engines.
=> chore: adding package-lock.json for engine changes

src/index.ts, tests/fixtures/arm64.output.service.json, tests/fixtures/debug-log-level.output.service.json, tests/fixtures/debug.output.service.json, tests/fixtures/distributed-tracing-enabled.output.service.json, tests/fixtures/eu.output.service.json, tests/fixtures/function-has-layers.output.service.json, tests/fixtures/include.output.service.json, tests/fixtures/includes-all-provider-layer.output.service.json, tests/fixtures/lambda-extension-disabled.output.service.json, tests/fixtures/lambda-extension-enabled.output.service.json, tests/fixtures/license-key-secret-disabled.output.service.json, tests/fixtures/log-disabled.output.service.json, tests/fixtures/log-ingestion-via-extension.output.service.json, tests/fixtures/log-level.output.service.json, tests/fixtures/manual-wrapping.output.service.json, tests/fixtures/node-versions.output.service.json, tests/fixtures/provider-environment-log-level.output.service.json, tests/fixtures/provider-environment.output.service.json, tests/fixtures/provider-layer.output.service.json, tests/fixtures/proxy.output.service.json, tests/fixtures/stage-included.output.service.json, tests/fixtures/trusted-account-key-excluded.output.service.json, tests/fixtures/trusted-account-key-included.output.service.json
- This PR provides support to ruby 3.4 layers
- Updated the test cases.
=> feat: support to ruby 3.4

README.md, src/index.ts
Introduces APM Mode for limited release
This has been tested with new deployment of Lambda
=> feat: apm fusion mode

README.md
- This PR improves the documentation for the `NR.Apm.Lambda.Mode: true` provider tag by clarifying its purpose and relationship to **APM + Serverless Convergence feature**
Related Links
[[APM + Serverless Convergence Documentation])](https://docs-preview.newrelic.com/docs/apm-serverless-convergence)
=> feat: Updated Readme for Provider Tags
